name: lint

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

cache-mode: none

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: openai/fence@530cce8d45da60a7c353da45511639ad5e154e9a # pin@v0.10.1

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v6
        with:
          persist-credentials: false

      - name: setup go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # pin@v6
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: bootstrap
        run: script/bootstrap

      - name: lint
        run: script/lint
