name: release

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  release:
    if: github.repository == 'grantbirki/go-template' # change this to your repository
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}

    steps:
      - name: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # pin@v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: setup go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # pin@v6.1.0
        with:
          go-version-file: "go.mod"
          cache: false

      - name: bootstrap
        run: script/bootstrap

      - name: build +release
        run: script/build --release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # pin@v7.0.0
        id: upload-artifact
        with:
          name: dist
          path: dist/
          retention-days: 5
          if-no-files-found: error

  sign:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: read
    steps:
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # pin@8.0.0
        with:
          artifact-ids: ${{ needs.release.outputs.artifact-id }}
          path: "dist/"

      - name: attest build provenance
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # pin@v4.1.0
        with:
          subject-path: "dist/"

  verify:
    permissions: {}
    runs-on: ubuntu-latest
    needs: [release, sign]
    steps:
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # pin@8.0.0
        with:
          artifact-ids: ${{ needs.release.outputs.artifact-id }}
          path: "dist/"

      - name: verify
        env:
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          ARTIFACT_PATH: "dist/"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Scanning for files in $ARTIFACT_PATH"

          # Find all regular files in the artifact path recursively
          find "$ARTIFACT_PATH" -type f | while read -r file; do
            echo "Verifying file: $file"
            
            # Log the command that will be executed
            echo "Executing command: gh attestation verify \"$file\" --repo ${OWNER}/${REPO} --signer-workflow ${OWNER}/${REPO}/.github/workflows/release.yml"
            
            # Run the command
            gh attestation verify "$file" --repo ${OWNER}/${REPO} --signer-workflow ${OWNER}/${REPO}/.github/workflows/release.yml
          done
